import glob from "glob"
const fs = require("fs")
const path = require("path")

let getPages;
if (process.env.NODE_ENV === "production") {
  const pagesManifest = JSON.parse(fs.readFileSync(path.join(__dirname, "../../", "pages-manifest.json")))
  let pages = Object.keys(pagesManifest)
  const autoGeneratedPages = ["/", "/_app", "/404", "/_document", "/_error"]
  pages = pages.filter(dir => !autoGeneratedPages.includes(dir) && !dir.startsWith("/api"))

  getPages = (req, res) => {
    res.status(200).send(pages)
  }
}
else {
  getPages = (req, res) => {
    const cwd = __dirname.substr(0, __dirname.length - "\\build-dev\\server\\pages\\api".length) + "\\pages"
    glob('**\\', { cwd }, (err, directories) => {
      directories = directories.map(dir => dir.substring(0, dir.length - 1))
      directories = directories.filter(dir => !["api"].includes(dir))
      res.status(200).send(directories)
    })
  }
}

export default getPages;